### PR TITLE
Updated readme to include Line-us JS Kit

### PR DESCRIPTION
**Pull request by funwithtriangles**

### CODE REVIEW

**Comment by robertpoll** [comment]
Very nice! Thanks a lot for taking the time to do this. Would be really interesting to be able to use it to preview gcode as well as javascript drawings.

**Comment by funwithtriangles** [comment]
No problem, had fun making it! So you're saying parse the gcode instead of the JS commands? That does make sense for it to be useable with other languages (although those languages would still need to connect to the JS page somehow...). Is that what you were thinking?

**Comment by robertpoll** [comment]
Yes, exactly. It would mean that people could generate gcode without having to worry about how to get it to Line-us. Being able to see the output on screen before you send is also a huge benefit. A simple file upload would probably be good enough to get files to the page I guess..? 

One other thing, we've been working on a new version of the line-us firmware that supports websockets - we're doing it primarily to enable our Scratchx extension but it obviously opens up non Node JS. Let me know if you're interested in testing and I'll add you to the list - I'll just need your machine serial number - it's in the 'hello' message:

```
[0] Received: hello VERSION:"1.0.2Beta2 May  9 2018 16:28:35" NAME:line-us SERIAL:9651240
```

**Comment by funwithtriangles** [comment]
I'd imagine a simple text box would be easiest? I've created an issue over on the [repo](https://github.com/funwithtriangles/line-us-js-kit/issues/2) so it's now on the list. Add any more comments/ideas there. :)

Websockets sound fun! Not sure how much time I have to play in the coming weeks but would happily be on that list! Serial is **990231**.

**Comment by robertpoll** [comment]
Great - thanks. I've added your machine to the list. In the App, drag the top right menu to the left to get to settings and you'll see firmware update. Takes between 30s and a couple of minutes and Line-us will re-start and wave its arm when it's done. Its important not to power off Line-us during the update.

**Comment by codybenlewis** [comment]
I spent some time starting a basic library, but couldn’t make any progress with the drawing preview. 

Processing seemed to be the natural fit, but since Line-Us’s calls all happen in a single iteration, it created some conflicts with Processing’s main drawing loop. 

With Processing, graphics render in a buffer each iteration before drawing to the screen. Previews would only display after Line-Us had already finished drawing, and then the program would exit.

There probably exists a world where we can program drawing functions, and then call Line-Us to copy and execute them in one call, but the challenge is not requiring users to type everything twice. I'm interested in discussing potential solutions.

For now, I’ve settled for working without the preview, which has allowed me to transfer to developing in Python. It’s faster connection/drawing speeds we’re a more than acceptable compromise. The library will then have functions similar to Processing for basic geometry and a remapped x/y coordinate plane. (0x - 500x, 0y - 1000y). Hopefully I’ll have more time to work on it soon.

**Comment by robertpoll** [comment]
Would be interested to see an example of the Processing issue if you have some code you  can share. As you say it's a natural fit so would like to see if we can solve the problem. A Python library will also be a great thing, so keep us up to date on how it goes. Just one last thing, we've set up a Forum for Line-us - we'll be announcing it soon but it's up and running at forum.line-us.com if you're interested.

**Pull request merged**
